// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADxZtVlc-XWzfunCr0msdVXmNR3RURu6w',
    appId: '1:699313682803:web:e4cfbe3ad826d9c8f8ad06',
    messagingSenderId: '699313682803',
    projectId: 'hemenyukle-dc9ec',
    authDomain: 'hemenyukle-dc9ec.firebaseapp.com',
    storageBucket: 'hemenyukle-dc9ec.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAI6sDdT5XbzZg-Tye4EP3SIVuPwTDA4sA',
    appId: '1:699313682803:android:961c24be6d3d2813f8ad06',
    messagingSenderId: '699313682803',
    projectId: 'hemenyukle-dc9ec',
    storageBucket: 'hemenyukle-dc9ec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIHHwuzUSpeEoKeiGlCigtNrq8jqxYslI',
    appId: '1:699313682803:ios:691bda5ca8887db9f8ad06',
    messagingSenderId: '699313682803',
    projectId: 'hemenyukle-dc9ec',
    storageBucket: 'hemenyukle-dc9ec.appspot.com',
    iosClientId:
        '699313682803-ofidu8oer1596q0h8sdoafoamndtnutc.apps.googleusercontent.com',
    iosBundleId: 'com.example.hemenyukle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIHHwuzUSpeEoKeiGlCigtNrq8jqxYslI',
    appId: '1:699313682803:ios:691bda5ca8887db9f8ad06',
    messagingSenderId: '699313682803',
    projectId: 'hemenyukle-dc9ec',
    storageBucket: 'hemenyukle-dc9ec.appspot.com',
    iosClientId:
        '699313682803-ofidu8oer1596q0h8sdoafoamndtnutc.apps.googleusercontent.com',
    iosBundleId: 'com.example.hemenyukle',
  );
}
